################################################################################
# basen on an autogenerated makefile
# TODO convert to automake, not jinja
################################################################################

-include ../makefile.init

# All of the sources participating in the build are defined here
-include sources.mk
-include objects.mk
-include subdir.mk

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(C_DEPS)),)
-include $(C_DEPS)
endif
endif

PROJECT_NAME := app
BUILD_DIR := build
# Add inputs and outputs from these tool invocations to the build variables
PARTIAL_LINK_EXE += \
$(BUILD_DIR)/USER_OBJS.o \

ELF_EXECUTABLES += \
$(BUILD_DIR)/USER_OBJS.elf \


# Add inputs and outputs from these tool invocations to the build variables

C_SRCS += \
	main.c \


OBJS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SRCS:.c=.o)))

C_DEPS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SRCS:.c=.d)))

C_INC = \
	-Iinclude \


# standard "all" target
all: $(BUILD_DIR) out.ex3

# Linker and tool invocations
out.ex3: $(ELF_EXECUTABLES)
	@echo 'Building target: $@'
	@echo 'Invoking: Elf2ARMC'
	elf2armc  $(ELF_EXECUTABLES) $(PROJECT_NAME).ex3
	@echo 'Finished building target: $@'
	@echo ' '

$(BUILD_DIR)/USER_OBJS.o: $(OBJS) $(USER_OBJS)
	@echo 'Invoking: C Linker'
	arm-none-eabi-ld $(OBJS) $(USER_OBJS) $(LIBS) -T"/hpgcc3/lib/romentries.list" -i /hpgcc3/lib/RLloader.o -L/hpgcc3/lib -o $(PARTIAL_LINK_EXE)
	@echo 'Finished building: $@'
	@echo ' '

$(BUILD_DIR)/USER_OBJS.elf: $(PARTIAL_LINK_EXE) $(USER_OBJS)
	@echo 'Invoking: C Linker (2nd stage)'
	arm-none-eabi-ld $(PARTIAL_LINK_EXE) $(USER_OBJS) $(LIBS) -T"/hpgcc3/lib/RLld.script" -nodefaultlibs -nostdlib -L/hpgcc3/lib -larmggl -larmhplib -larmhpg -larmhplib -larmfsystem -larmhplib -larmdecnumber -larmhplib -larmgcc -o $(ELF_EXECUTABLES)
	@echo 'Finished building: $@'
	@echo ' '


# Each subdirectory must supply rules for building sources it contributes
$(BUILD_DIR)/%.o: %.c
	@echo 'Building file: $<'
	@echo 'Invoking: C Compiler'
	arm-none-eabi-gcc -mlittle-endian -mtune=arm920t -mcpu=arm920t -fomit-frame-pointer -msoft-float -mthumb-interwork -I/hpgcc3/include $(C_INC) -Os -gdwarf-2 -Wall -c -o "$@" "$<" && \
	echo -n '$(@:%.o=%.d)' $(dir $@) > '$(@:%.o=%.d)' && \
	arm-none-eabi-gcc -MM -MG -P -w -mlittle-endian -mtune=arm920t -mcpu=arm920t -fomit-frame-pointer -msoft-float -mthumb-interwork -I/hpgcc3/include $(C_INC) -Os -gdwarf-2 -Wall -c   "$<" >> '$(@:%.o=%.d)'
	@echo 'Finished building: $<'
	@echo ' '

# Other Targets
$(BUILD_DIR):
	mkdir $@

clean:
	rm -rf $(BUILD_DIR) $(PROJECT_NAME).ex3

.PHONY: all clean dependents
